

version: '2'
services:
  mysql:
    container_name: docker_mysql
    restart: always
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: '123456' # TODO: Change this
      MYSQL_USER: 'localhost'
      MYSQL_PASS: '123456'
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  my-datavolume: